### ISSUE TITLE
Is it possible to make write action and then read action at once?

### ISSUE THREAD

**Issue by tereshchenkoartyom94** [whitedogg13/react-native-nfc-manager#120]
I can not read NDEF message immediately after write. The message stays the same. I have found that I need to call 

NfcManager.closeTechnology();
NfcManager.unregisterTagEvent();
NfcManager.registerTagEvent();
NfcManager.requestNdefTechnology();

To read new tag information, but NfcManager.requestNdefTechnology() do not trigger success callback until I move away a phone from NFC tag and move it back. Could you please tell me what I am doing wrong and what I should to do to succeed with WRITE and then READ operation not moving my phone away from NFC tag?

**Comment by whitedogg13** [comment]
Hi @tereshchenkoartyom94 thanks for reporting! Also sorry for the late response, kinda busy recently.

I can reproduced this issue using my Nokia 7. Read the tag after writing it will bring us the old content, even we leave some delay time, the issue remains.

However it isn't the expected behavior, from the android doc, once we call [`getNdefMessage`](https://developer.android.com/reference/android/nfc/tech/Ndef.html#getNdefMessage()) it should read `current content` from the NFC tag rather than the cached one (there's a separated API called [`getCachedNdefMessage`](https://developer.android.com/reference/android/nfc/tech/Ndef.html#getCachedNdefMessage()) for this) 

 I will try to write a simple native program to verify this behavior when I'm available.

BTW, just wonder, why do you want to read the tag content back? If what you need is to confirm the tag has been successfully written, you don't need to do that. Android will throw exceptions when the write operation fails, and our library will transform the exception to a promise rejection.

Thanks!

**Comment by tereshchenkoartyom94** [comment]
I am working on an app that interacts with a meter hardware and the NFC tag is just a buffer to communicate. I write commands to this tag, then microcontroller of hardware takes this command and updates NFC tag content with a response

**Comment by whitedogg13** [comment]
Got it, it's a cool application! I will see what I can do and keep you posted.

**Comment by tereshchenkoartyom94** [comment]
Thank you @whitedogg13. BTW Thank you for your awesome work on this library, especially for adding NDEF utils, that was very helpful for my project!

**Comment by whitedogg13** [comment]
@tereshchenkoartyom94 finally got some time working on this, and it's indeed a library issue. It should be fixed in latest release (v1.1.3), please check it out!

BTW, sorry for being so late for this fix and hope that I can manage this more efficiently in future :)

**Comment by tereshchenkoartyom94** [comment]
@whitedogg13 Thanks a lot!

**Comment by whitedogg13** [comment]
It's good to help. I will close this issue for now, just tell me if you encounter any problems!
