### ISSUE TITLE
how can I authenticate with MifareUltralight ?

### ISSUE THREAD

**Issue by bluetiger30** [whitedogg13/react-native-nfc-manager#132]
Hi , is there an authentication function to authenticate with MifareUltralight C? or is the transceive function the authentication function for MifareUltralight, if so can you kindly help me out with an example?

**Comment by whitedogg13** [comment]
Hi @bluetiger30 , as far as I know, Android doesn't expose such API.

Android API for `MifareUltralight` is listed here: https://developer.android.com/reference/android/nfc/tech/MifareUltralight, and no authentication related ones are included.

**Comment by JamesZhange** [comment]
I can use NFC tools app like 'NFC Tools Pro' to authenticate my MifareUltralight C, how they do that?

**Comment by whitedogg13** [comment]
@JamesZhange sorry for the late response.

It's possible to use the low-level `transceive` API to approach this feature, but it requires a deep understanding for `MifareUltralight C` tag command set. 

Since I'm not an expert for this tag, I will label this issue as help wanted and see if someone can help us!

Thanks!

**Comment by whitedogg13** [comment]
close inactive issue
