### ISSUE TITLE
Android Error on NfcManager.start()

### ISSUE THREAD

**Issue by MaxBolotnyi** [whitedogg13/react-native-nfc-manager#160]
Just installed the lib and tested with the following code to see if it works.

I am using redux-saga, here is the sample code that did not work for me.

`function* nfcWatcher(api) {
  while (true) {
    try {
      const action = yield take(TRANSFERS_SCAN_NFC);
        
      // will fall back to the catch here if the NFC is not supported on device.
      const nfcProcess = yield call(NfcManager.start);
        
    } catch {
      Alert.alert(
        'NFC Warning',
        'This device does not support NFC',
        [
          {
            text: 'OK',
            onPress: () => NavActions.pop(),
          }
        ]
      )
      console.log('CATCH - nfcWatcher!!!!!!!!');
    }
  }
}`

The following error happens (screen attached)

![Screenshot_20190527-165846](https://user-images.githubusercontent.com/36646205/58425825-87548a80-80a3-11e9-95ab-3b7f0b907f6a.jpg)

If I comment this out in your library, the app does not crash anymore.
<img width="856" alt="Снимок экрана 2019-05-27 в 17 19 38" src="https://user-images.githubusercontent.com/36646205/58425906-c5ea4500-80a3-11e9-8226-ca67759692e7.png">

Please, advice.

**Comment by whitedogg13** [comment]
Hi @MaxBolotnyi sorry for the late response. 

I'm not using saga, but from the code I can guess what's going wrong.
In your code, you have extract the `NfcManager.start` function like this: 
```javascript
const nfcProcess = yield call(NfcManager.start);
```
You can change it to:
```javascript
const nfcProcess = yield call(() => NfcManager.start());
```

The reason is, In your original code, the `this` is not bond to `NfcManager` (because we didn't use arrow function for NfcManager.js, we will consider to change that in later release).

Please retry and tell me if there's still anything going wrong.

**Comment by whitedogg13** [comment]
close inactive issue
