### ISSUE TITLE
iOS Beta 2

### ISSUE THREAD

**Issue by jafri** [whitedogg13/react-native-nfc-manager#185]
I see that you use

```
      let resp = await NfcManager.requestTechnology('ndef');
```

Shouldn't the tech be NfcTech.Ndef which resolves to 'Ndef'

**Comment by whitedogg13** [comment]
Good catch! That’s because currently the two(iOS/android) platforms are different in their API design, so we want to limit the impact for Android during iOS 13 dev to avoid any accidents, even for simple defines.

Of cause, we will eventually try to sync up the exposed APIs for both platforms, but maybe in later dev stage.

**Comment by jafri** [comment]
I see @whitedogg13 so should I be using `ndef` for iOS and `Ndef` for android?

**Comment by whitedogg13** [comment]
Sadly that’s a yes for now. Thanks for the understanding^^

**Comment by jafri** [comment]
No problem @whitedogg13, one more question. `closeTechnology`, is that now available on IOS, like `cancelTechnologyRequest`? Or is it not needed on iOS

**Comment by whitedogg13** [comment]
Not available, please use `cancelTechnologyRequest` for now.
