### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by yanielbf** [whitedogg13/react-native-nfc-manager#191]
I copied your example code. When receiving the event only send me an object with this format 
{typeTech: [isoDep, TechA], id: xxxxxxx}. How to parse this result. Help me. Thank

**Comment by whitedogg13** [comment]
@yanielbf Sorry for the late response. For `IsoDep` tech type, you will need to send APDU to the tag in order to communicate with it. There’re no standard way to `parse` this kind of tag. You can refer to [here](https://www.google.com.tw/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiB0oWlxrnkAhW8yYsBHQo2CM4QFjAAegQIAxAB&url=https%3A%2F%2Fdeveloper.android.com%2Freference%2Fandroid%2Fnfc%2Ftech%2FIsoDep&usg=AOvVaw3T0VH8TMvH8wquLk7WOeHi) for more info.

**Comment by tcagkansokmen** [comment]
@whitedogg13 hi bro, how can we get APDU to send as command?

I'm trying to decode message on id card, but it returns non-meaningful data to me.

How can I get name-surname etc?

**Comment by Abramovick** [comment]
> how can we get APDU to send as command?

Hi @tcagkansokmen, Did you manage to figure this out?
