### ISSUE TITLE
V2Iso15693 invalid tag ID  (iOS)

### ISSUE THREAD

**Issue by Megatron4537** [whitedogg13/react-native-nfc-manager#267]
On Android reading an NfcV (ISO15963 on iOS) tag will return a tag with an id 
**AD3C117E000104E0**

reading the same tag on iOS using the V2Iso15963 API to get the tag's ID will return a tag with an id
**E00401007E113CAD**

The same tag is returning two different IDs on each OS. I believe the Android tag ID is correct and wrong on iOS. Interestingly, reversing the ID on iOS is similar, but not exactly, some values are swapped together.

I used the [nfc-test-app](https://github.com/whitedogg13/nfc-test-app) to verify and the issue is present there too (I copied components `react-native-nfc-manager/example/AppV2Iso15693`, `react-native-nfc-manager/example/AppV2Index`, `react-native-nfc-manager/example/AppV2` components and added console.log(tag)) 

method used on Android
`NfcManager.setEventListener(NfcEvents.DiscoverTag, tag=>tag)`

method used on iOS
`await NfcManager.requestTechnology([NfcTech.Iso15693IOS]);
  const tag = await NfcManager.getTag();
`

**Comment by whitedogg13** [comment]
Hi @Megatron4537 Nice catch, thanks for reporting this!

I believe its something like [endianness](https://en.wikipedia.org/wiki/Endianness) issue. 

The tag `id` in native platform is reported as a `byte array`, and we simply convert it into a hex string one by one, then send back to JS layer. So the issue is because `iOS` and `Android` has their id array in reverse order when dealing with `15693` tag.

For example:
* in Android, the id is [0xAD, 0x3C, 0x11 0x7E, 0x00, 0x01, 0x04, 0xE0]
* in iOS, the id is [0xE0, 0x04, 0x01, 0x00, 0x7E, 0x11, 0x3C, 0xAD]

It might be an iOS platform bug, but I think it's safer to swap the byte order in your application code for now. 

Thanks!
