### ISSUE TITLE
Doesn’t work in production

### ISSUE THREAD

**Issue by waraness** [whitedogg13/react-native-nfc-manager#294]
It works perfectly on simulator, but nothing works in Production (on TestFlight and Android). For exemple my phone is nfc compatible (iPhone X) and it works when I test my app with xCode. But since I try it on Testflight it look like my phone is not compatible (I display an element with isCompatible). On android it works fine during test on simulator but it crashes in production....

**Comment by whitedogg13** [comment]
Hi @waraness this library actually never works on simulator since it requires the actual NFC hardware. In order to use this library properly, some setups have to be made, you can use [this repo](https://github.com/whitedogg13/nfc-test-app) as a starting point. 

If there're still any issues, please feel free to ask!
