### ISSUE TITLE
Can't write NFC TAG - message "you should requestTagEvent first"

### ISSUE THREAD

**Issue by pedrotainha** [whitedogg13/react-native-nfc-manager#42]
Hi, i can read the tag properly, but i can't write.
It appear a warning "you should requestTagEvent first"

I'm using your APP as example to test before i make my app implementation.

I have my Huawei P8 connected as emulator.

If you need more information, let me know.

Thank you

**Comment by whitedogg13** [comment]
Hi, thanks for trying this library!

As the warning says, you should call `requestTagEvent` API first before invoking NDEF write ( `requestNdefWrite` API). That's because we can only write to a tag after we detect it.

If you're using the example app, you can see a button named "Start Tag Detection", first click it then try to write NDEF again and it should work.

Thanks!

**Comment by pedrotainha** [comment]
I thanks.
