### ISSUE TITLE
Can't send data between two devices

### ISSUE THREAD

**Issue by glowww** [whitedogg13/react-native-nfc-manager#68]
I'm trying to send a string from one device to another, but instead of the text I send I get "play.google.com/store/apps/details?id={myPackageName}&feature=beam"

I guess Android Beam is trying to redirect me to my app in the Play Store, but it's not there yet. Is there any way to just send text over NFC?

I run _startDetection with a button, I didn't add what's inside the render function to make the code shorter.

This is my code:

```
import React, { Component } from 'react'
import NfcManager, {NdefParser, NfcTech} from 'react-native-nfc-manager';

const RtdType = {
    URL: 0,
    TEXT: 1,
};

function buildTextPayload(valueToWrite) {
    const textBytes = strToBytes(valueToWrite);
    // in this example. we always use `en`
    const headerBytes = [0xD1, 0x01, (textBytes.length + 3), 0x54, 0x02, 0x65, 0x6e];
    return [...headerBytes, ...textBytes];
}

export default class Home extends Component {

  constructor(props) {
        super(props);
        this.state = {
            supported: true,
            enabled: false,
            isWriting: false,
            urlToWrite: 'AAAAAAAAA',
            rtdType: RtdType.TEXT,
            tag: {}
        }
    }

    componentDidMount() {
        NfcManager.isSupported()
            .then(supported => {
                this.setState({ supported });
                if (supported) {
                    this._startNfc();
                }
            })
    }

    componentWillUnmount() {
        if (this._stateChangedSubscription) {
            this._stateChangedSubscription.remove();
        }
    }

    render () {...}

    _startNfc() {
        NfcManager.start({
            onSessionClosedIOS: () => {
                console.log('ios session closed');
            }
        })
            .then(result => {
                console.log('start OK', result);
            })
            .catch(error => {
                console.warn('start fail', error);
                this.setState({supported: false});
            })

        if (Platform.OS === 'android') {
            NfcManager.getLaunchTagEvent()
                .then(tag => {
                    console.log('launch tag', tag);
                    if (tag) {
                        this.setState({ tag });
                    }
                })
                .catch(err => {
                    console.log(err);
                })
            NfcManager.isEnabled()
                .then(enabled => {
                    this.setState({ enabled });
                })
                .catch(err => {
                    console.log(err);
                })
            NfcManager.onStateChanged(
                event => {
                    if (event.state === 'on') {
                        this.setState({enabled: true});
                    } else if (event.state === 'off') {
                        this.setState({enabled: false});
                    } else if (event.state === 'turning_on') {
                        // do whatever you want
                    } else if (event.state === 'turning_off') {
                        // do whatever you want
                    }
                }
            )
                .then(sub => {
                    this._stateChangedSubscription = sub;
                    // remember to call this._stateChangedSubscription.remove()
                    // when you don't want to listen to this anymore
                })
                .catch(err => {
                    console.warn(err);
                })
        }
    }

    _onTagDiscovered = tag => {

        console.log('Tag Discovered', tag);
        this.setState({ tag });

        let text = this._parseText(tag);
        alert(text)
    }

    _startDetection = () => {
        NfcManager.writeNdefMessage(buildTextPayload("MY TEXT"))
        NfcManager.registerTagEvent(this._onTagDiscovered)
            .then(result => {

                console.log('registerTagEvent OK', result)
            })
            .catch(error => {
                console.warn('registerTagEvent fail', error)
            })
    }
```

**Comment by whitedogg13** [comment]
Hi, Android Beam uses `setNdefPushMessage`, but this lib currently doesn't bridge this API yet. I will try to implement this and keep you posted!

**Comment by whitedogg13** [comment]
Hi, I have added a new method `setNdefPushMessage` into latest release (0.5.2), and you can find a concrete example in `example/App.js`.

Please use latest release to try it, thanks!

**Comment by glowww** [comment]
I ended up doing my own native module because I was in a hurry. But anyways, thank you for your time!

**Comment by whitedogg13** [comment]
Cool, good for you :)

**Comment by ngocnguyen09910060** [comment]
Hello @glowww ,
I am building an app using smart phone same as NFC Tag. I think my app have same context with your issue.
I have built 2 app on 2 smart phone: smart phone A as NFC Reader and smart phone B as NFC Tag.
On app of smart phone B, i have a  button call _startDetection() same as you.
But when i touch 2 smart phone, "Touch to beam" screen is displayed and i tap it to send data instead of "Send data" button. Please explain to me.
Next, i want smart phone A send data automatically when touch it to NFC Reader. How can i do it ?
Please help me.
Thanks and best regards.

**Comment by smkamranqadri** [comment]
Same issue here.

**Comment by Muhammad-Altabba** [comment]
Hello @whitedogg13,
I preferred to add to this opened issue rather than opening a new one since it is basically the same. However, it is different, kindly tell me to open a new one.

I am confused with the documentation and not able to finger out how exactly a peer-to-peer NFC communication could be achieved with NFC and especially how to do it using this library.

The main unclear point I think is how I can create a Tag from one device and read that Tag from the other. All what I could see in the samples is for reading a Tag first then possibly writing to the other device. How to make an App (X) to write a Tag to another App (Y)? 

As you know, Android Beam has been deprecated with Android 10. So, we need to use the plane NFC communication for this. And to have it for Android and iPhone as well.


By the way, also I read some people writing about the same. For example here https://www.reddit.com/r/reactnative/comments/elsetr/nfc_peertopeer_communication/:

> I came across react-native-nfc-manager but the examples and documentation are a bit confusing to me.

Many thanks for the great library and for your support in advance.

**Comment by Muhammad-Altabba** [comment]
After doing some research. This library does not support initiating communication between 2 devices for P2P. 

However, to initiate communication, either Android Beam has to be used but it is already deprecated and stoped to be there at Android 10. Or the other way is to Emulate one of the devices as a Card to the other device. Another library for React Native exist: https://www.npmjs.com/package/react-native-nfc-hce. But it seems to be very old with outdated setup documentation. 

But, the Android Card Emulation code example has been archived: https://github.com/googlearchive/android-CardEmulation and the new sample codes and projects focus on using BlueTooth (check the samples at https://github.com/android/connectivity-samples). And on the other hand, iPhone does not support Card Emulation. So, it seems the manufacturers do not recommend and/or support the NFC P2P use case.
